remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: JeuStan
description: Choisi le bon pays
github:
  zip_url: https://github.com/lmlouis/JeuxStanHTML.git/download.zip
  another_url: https://github.com/lmlouis/JeuxStanHTML.git
